pipeline {
  agent any
  tools {
    jdk 'Java17'
    maven 'Maven'
  }
  stages {
    stage('Checkout Code') {
      steps {
        echo 'Pulling from Github'
        git branch: 'main', credentialsId: 'mygithubcred', url: 'https://github.com/Karthik-05-07/k8test.git'
      }
    }
    stage('Test Code') {
      steps {
        echo 'JUNIT Test case execution started'
        bat 'cd indiaproj && mvn clean test'
        
      }
      post {
        always {
		  junit '**/target/surefire-reports/*.xml'
          echo 'Test Run is SUCCESSFUL!'
        }

      }
    }
    stage('Build Project') {
      steps {
        echo 'Building Java project'
        bat 'cd indiaproj && mvn clean package -DskipTests'
      }
    }
    stage('Build the Docker Image') {
      steps {
        echo 'Building Docker Image'
        bat 'cd indiaproj && docker build -t myindiaproj:1.0 .'
      }
    }
    stage('Push Docker Image to DockerHub') {
      steps {
        echo 'Pushing  Docker Image'
        withCredentials([usernamePassword(
		    credentialsId: 'dockerpass',
		    usernameVariable: 'DOCKER_USER',
		    passwordVariable: 'DOCKER_PASS'
		)]) {
	    bat '''
	    echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
	    docker tag myjavaproj:1.0 %DOCKER_USER%/indiaproj:1.0
	    docker push %DOCKER_USER%/indiaproj:1.0
	    '''
		}
      }
    }
    /*stage('Run Docker Container') {
      steps {
        echo 'Running Java Application'
        bat '''
        docker rm -f myjavaproj-container || exit 0
        docker run --name myjavaproj-container myjavaproj:1.0
        
        '''               
      }
    }*/
	stage('Deploy Project to K8s') {
		steps {
			echo 'Deploy Java project to Kubernetes'
			bat '''
				minikube delete
				minikube start
				minikube image load tejeshwar144/myindiaproj:1.0
				kubectl apply f deployment.yaml
				kubectl apply f services.yaml
				kubectl get pods
				kubectl describe pods
				kubectl get services
				minikube addons enable dashboard
				minikube dashboard
			'''
			}
		}
  }
  post {
    success {
      echo 'BUild and Run is SUCCESSFUL!'
    }
    failure {
      echo 'OOPS!!! Failure.'
    }
  }
}
